apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-ypqp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-ypqp
    app.kubernetes.io/part-of: test-rhtap-64-app
  name: devfile-sample-code-with-quarkus-ypqp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-ypqp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-ypqp
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-64-tenant/test-rhtap-64-app/devfile-sample-code-with-quarkus-ypqp@sha256:2569d1402aba3e9505a41e67134e0f180a30f03ef3afa857ceafe497dcd1ee24
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
